name: my first code
on: 
  push:
    branches:
      - main
env:
  APP_ENV : "demo"
jobs:
  build1:
        runs-on: ubuntu-latest
        steps:
          - name: This is the 1st line 
            run: echo "1st line is running perfect"
  build2:
         runs-on: ubuntu-latest
         steps:
           - name: This is the 2nd line 
             run: echo "2nd line is running perfect"
  deploy:
         runs-on: ubuntu-latest
         steps:
           - name: Using variables in the GHA
             run: echo " Hello this is, ${{vars.My_Name}}"
  deploy1:
          runs-on: ubuntu-latest
          steps:
            - name: checking out the code 
              uses: actions/checkout@v4

            - name: printing the index.html file
              run:  cat index.html

  print_env:
          runs-on: ubuntu-latest
          steps:
            - name: using .env file
              run: echo "App is using $APP_ENV"
    
  
