name: my first code
on: 
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build1:
        runs-on: ubuntu-latest
        steps:
          - name: This is the 1st line 
            run: echo "1st line is running perfect"
  build2:
         runs-on: ubuntu-latest
         steps:
           - name: This is the 2nd line 
             run: echo "2nd line is running perfect"
        
    
  
