name: My First Workflow

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v4
        
      - name: installing package.json
        run:  npm init -y

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm run dev
